# Generated by Django 5.0.6 on 2024-05-22 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('basket_icon_click', models.IntegerField()),
                ('basket_add_list', models.IntegerField()),
                ('basket_add_detail', models.IntegerField()),
                ('sort_by', models.IntegerField()),
                ('image_picker', models.IntegerField()),
                ('account_page_click', models.IntegerField()),
                ('promo_banner_click', models.IntegerField()),
                ('detail_wishlist_add', models.IntegerField()),
                ('list_size_dropdown', models.IntegerField()),
                ('closed_minibasket_click', models.IntegerField()),
                ('checked_delivery_detail', models.IntegerField()),
                ('checked_returns_detail', models.IntegerField()),
                ('sign_in', models.IntegerField()),
                ('saw_checkout', models.IntegerField()),
                ('saw_sizecharts', models.IntegerField()),
                ('saw_delivery', models.IntegerField()),
                ('saw_account_upgrade', models.IntegerField()),
                ('saw_homepage', models.IntegerField()),
                ('device_computer', models.IntegerField()),
                ('device_tablet', models.IntegerField()),
                ('returning_user', models.IntegerField()),
                ('propensity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
