# Generated by Django 5.0.6 on 2024-05-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_useraction_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='UserID',
            field=models.CharField(verbose_name=255),
        ),
    ]
