# Generated by Django 5.0.6 on 2024-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='UserID',
            field=models.CharField(max_length=255),
        ),
    ]
