# Generated by Django 5.0.6 on 2024-05-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=255)),
                ('basket_icon_click', models.IntegerField()),
                ('basket_add_list', models.IntegerField()),
                ('basket_add_detail', models.IntegerField()),
                ('sort_by', models.IntegerField()),
                ('image_picker', models.IntegerField()),
                ('account_page_click', models.IntegerField()),
                ('promo_banner_click', models.IntegerField()),
                ('detail_wishlist_add', models.IntegerField()),
                ('list_size_dropdown', models.IntegerField()),
                ('closed_minibasket_click', models.IntegerField()),
                ('checked_delivery_detail', models.IntegerField()),
                ('checked_returns_detail', models.IntegerField()),
                ('sign_in', models.IntegerField()),
                ('saw_checkout', models.IntegerField()),
                ('saw_sizecharts', models.IntegerField()),
                ('saw_delivery', models.IntegerField()),
                ('saw_account_upgrade', models.IntegerField()),
                ('saw_homepage', models.IntegerField()),
                ('device_computer', models.IntegerField()),
                ('device_tablet', models.IntegerField()),
                ('returning_user', models.IntegerField()),
                ('propensity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account_page_click',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='basket_add_detail',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='basket_add_list',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='basket_icon_click',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='checked_delivery_detail',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='checked_returns_detail',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='closed_minibasket_click',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='detail_wishlist_add',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='device_computer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='device_tablet',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image_picker',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='list_size_dropdown',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='promo_banner_click',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='propensity',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='returning_user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='saw_account_upgrade',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='saw_checkout',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='saw_delivery',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='saw_homepage',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='saw_sizecharts',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sign_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sort_by',
        ),
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='UserID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
