# Generated by Django 5.0.6 on 2024-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_actioncustomer_remove_customer_account_page_click_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actioncustomerlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(blank=True, db_column='UserID', null=True)),
                ('basket_icon_click', models.BigIntegerField(blank=True, null=True)),
                ('basket_add_list', models.BigIntegerField(blank=True, null=True)),
                ('basket_add_detail', models.BigIntegerField(blank=True, null=True)),
                ('sort_by', models.BigIntegerField(blank=True, null=True)),
                ('image_picker', models.BigIntegerField(blank=True, null=True)),
                ('account_page_click', models.BigIntegerField(blank=True, null=True)),
                ('promo_banner_click', models.BigIntegerField(blank=True, null=True)),
                ('detail_wishlist_add', models.BigIntegerField(blank=True, null=True)),
                ('list_size_dropdown', models.BigIntegerField(blank=True, null=True)),
                ('closed_minibasket_click', models.BigIntegerField(blank=True, null=True)),
                ('checked_delivery_detail', models.BigIntegerField(blank=True, null=True)),
                ('checked_returns_detail', models.BigIntegerField(blank=True, null=True)),
                ('sign_in', models.BigIntegerField(blank=True, null=True)),
                ('saw_checkout', models.BigIntegerField(blank=True, null=True)),
                ('saw_sizecharts', models.BigIntegerField(blank=True, null=True)),
                ('saw_delivery', models.BigIntegerField(blank=True, null=True)),
                ('saw_account_upgrade', models.BigIntegerField(blank=True, null=True)),
                ('saw_homepage', models.BigIntegerField(blank=True, null=True)),
                ('device_computer', models.BigIntegerField(blank=True, null=True)),
                ('device_tablet', models.BigIntegerField(blank=True, null=True)),
                ('returning_user', models.BigIntegerField(blank=True, null=True)),
                ('loc_uk', models.BigIntegerField(blank=True, null=True)),
                ('propensity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actionCustomerList',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ActionCustomer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
